databases:
  - name: postgres
    ipAllowList: []
    databaseName: take-home_project
    user: take-home_project

services:
  - type: web
    name: take-home_project
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false